### PR TITLE
Update for Julia 1.8

### PR DESCRIPTION
**Pull request by ianfiske**
Addresses #15

### CODE REVIEW

**Review by mattBrzezinski — APPROVED** [review]

**Comment by mattBrzezinski** [comment]
I never ended up being able to get around to writing an integration test for this package, would you be able to confirm that you can launch a `HelloWorld` or similar test here @ianfiske ?

**Comment by ianfiske** [comment]
Yes, I have a successfully launched `HelloWorld` with this changes in the PR.

**Comment by mattBrzezinski** [comment]
Sweet! I think it just needs a bump to the `Project.toml` version and it's good to go!

**Comment by ianfiske** [comment]
Cool, I just bumped the patch version to 0.1.3.  Let me know if you wanted to bump the minor instead.

**Pull request merged**
